DeveloperKnot/Home_page

client/package-lock.json, client/package.json
=> Added redux dependencies

client/src/App.jsx
- setted up redux
- added a simple component to test it out
=> setup: redux

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/pages/Products.jsx
=> add: product page filter & price section

client/src/pages/Products.jsx
=> added offers and discount accordion features

.vscode/settings.json, client/.vscode/settings.json, client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/Button.jsx, client/src/components/Card.jsx, client/src/components/Comp1.jsx, client/src/components/Comp2.jsx, client/src/components/Components.jsx, client/src/components/Footer.jsx, client/src/components/MyCarousel.jsx, client/src/components/Navbar.jsx, client/src/pages/Categories.jsx, client/src/pages/Home.jsx, client/src/pages/Products.jsx
Categories Page(/categories)
Home page:
=> setup: formatting and routing

client/src/App.jsx, client/src/pages/Categories.jsx
=> added products in product page

client/src/components/FAQls.css, client/src/components/FAQls.jsx, client/src/pages/FAQ.jsx
=> Minor changes

client/src/App.jsx, client/src/pages/About.jsx
=> made about page and added the information about the company

client/src/components/FAQhelp.jsx, client/src/components/comp3About.jsx, client/src/pages/About.jsx
- Reverts DeveloperKnot/Home_page#35
- Changes done in this for the proper functionality
=> Revert "Revert "Added Vision and Goals section""

client/src/components/FAQls.jsx
- the faq accordion section is dynamic now
- achieved throught useState
- uses onclick event for the trigger
- ![image](https://github.com/DeveloperKnot/Home_page/assets/72339688/cbc958ac-3da5-4552-b251-2b07a502033a)
=> add: dynamic faq fundtionality with state

client/src/App.jsx, client/src/pages/Default.jsx
=> 404 page animation completed

client/src/App.jsx, client/src/pages/Login.jsx
=> complete login page

client/src/pages/Seller.jsx
refactored the code, for a proper integration
=> refactor: code

client/src/App.jsx, client/src/components/AccountInformation.jsx, client/src/pages/SellerRegistrationForm.jsx
=> add: seller registration page and account information

client/src/pages/SellerProfile.jsx
=> add: review section

client/src/App.jsx, client/src/components/AddToCartAndReviews.jsx, client/src/components/MyAccordion.jsx, client/src/pages/Product.jsx
=> add: product page reviews and add to cart

client/src/components/SellerStoryWatchTab.jsx, client/src/pages/SellerStory.jsx
=> add: sellerstorywatchtab

client/src/components/SellerStroyFeaturedTab.jsx, client/src/pages/SellerStory.jsx
=> add: make the seller story featured subsection

client/src/components/Components.jsx, client/src/components/Navbar.jsx, client/src/components/Sidebar.css, client/src/components/Sidebar.jsx, client/src/pages/Home.jsx
=> added side navigation bar and some changes in the code in home page

client/src/components/AddToCartAndReviews.jsx
=> add: made for you section

.vscode/settings.json, client/src/components/Navbar.jsx, client/src/components/Sidebar.css, client/src/components/Sidebar.jsx
=> enhnaced navbar

client/src/components/Payment.jsx, client/src/components/PaymentMethod.jsx, client/src/components/ShippingAddress.jsx
=> completed the whole payment's page
